"""
Config module.

WARNING: Do not edit this file as it is versioned and for default values.
Rather create a local config file as per the README and set your overrides
there.
"""

# Github API token to authenticate with. This is must be set - see the README.
ACCESS_TOKEN = ''

# Paths for repos to report on (as account name and then repo name).
# Only lookup activity within these repos.
REPO_PATHS = (
    'MichaelCurrin/aggre-git',
)
# Username of user or organization. Only lookup activity in repos under this
# account. This does not have to correspond to the REPO_NAMES value as when
# this is used it is used in place of REPO_NAMES.
REPO_OWNER = 'MichaelCurrin'

# If True, then lookup all repos within configured REPO_OWNER. Otherwise only
# lookup activity within REPO_NAMES.
BY_OWNER = False

# Lookup activity for these Github users. Note only activity within the
# selected repos will be counted, as set in either REPO_NAMES or REPO_OWNER.
USERNAMES = ('MichaelCurrin',)


try:
    from .configlocal import *
except ImportError:
    import os
    f_path = os.path.join(os.path.dirname(__file__), 'configlocal.py')
    raise ImportError("You need to create the missing file"
                      " at {}".format(f_path))

assert ACCESS_TOKEN, "Please set the ACCESS_TOKEN value in the local config" \
                     " file"
